### ISSUE TITLE
Maxage for a numbers model and plusgroups

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/MSEtool#1]
Should be similar I think:

makeOM<-function(maxage){
  nyears<-69
  proyears<-50
  SLOM <-OMtool::testOM
  SLOM@Msd <-c(0.02,0.02)
  SLOM@nyears <- nyears <- nyears
  SLOM@proyears <- proyears <-proyears
  SLOM@maxage <-maxage-1
  SLOM@nsim <- 48
  SLOM@M <-rep(0.1,2)
  SLOM@h <-rep(0.29,2)
  SLOM@cpars$R0 <-runif(nsim,1600,2000) # initial guess at carrying capacity
  SLOM@cpars$Find <-array(1E-6,c(nsim,nyears))
  SLOM@cpars$Perr_y <-array(trlnorm(nsim*(maxage+proyears+nyears-1),1,0.1),c(nsim,maxage+proyears+nyears-1))
  SLOM@cpars$Perr_y[,1:maxage] <-runif(nsim,0.02,0.03)
  SLOM@cpars$Mat_age <-array(rep(c(0.01,0.5,seq(0.99,1,length.out=maxage-2)),each=nsim),c(nsim,maxage,nyears+proyears))
  SLOM@cpars$Wt_age <-array(rep(c(0.01,0.5,seq(0.99,1,length.out=maxage-2)),each=nsim),c(nsim,maxage,nyears+proyears))
  SLOM@cpars$Len_age<-array(rep(c(0.01,0.5,seq(0.99,1,length.out=maxage-2)),each=nsim),c(nsim,maxage,nyears+proyears))
  SLOM@cpars$V <- array(rep(c(0.01,0.25,0.5,0.75,rep(1,21)),each=nsim),c(nsim,maxage,nyears+proyears))
  SLOM@cpars$b <-rep(1,nsim)
  SLOM@cpars$a <-rep(1,nsim)
  SLOM@cpars$qs <-rep(1,nsim)
  SLOM@cpars$Linf <-rep(1,nsim)
  SLOM@cpars$K <-rep(1,nsim)
  SLOM@cpars$t0 <-rep(0,nsim)
  SLOM@Prob_staying <-SLOM@Frac_area_1<-c(0.5,0.5)
  SLOM
}

test1<-OMtool::runMSE(makeOM(8),Hist=T)
test2<-OMtool::runMSE(makeOM(25),Hist=T)

Ns1<-apply(test1@TSdata$Biomass,1:2,sum)
Ns2<-apply(test2@TSdata$Biomass,1:2,sum)

matplot(2019-(68:0),t(Ns1),type='l', ylim=c(0,12000),yaxs='i',ylab="Sea Lion Numbers (North of 51 degrees) ",xlab="Year",col="#0000ff40",lwd=2,lty=1)
matplot(2019-(68:0),t(Ns2),type='l', ylim=c(0,12000),yaxs='i',col="#ff000040",lwd=2,lty=1,add=T)
abline(h=(0:20)*1000,col="#99999970")

**Comment by AdrianHordyk** [comment]
I think this is caused by many more years of process error that are present when maxage is higher.
