### ISSUE TITLE
Function to convert MOM to OM object

### ISSUE THREAD

**Issue by AdrianHordyk** [Blue-Matter/MSEtool#26]
Handy for testing if `runMSE` and `multiMSE` dynamics are consistent when simple fixed F MPs are used.

Also handy for testing if `multiMSE` is required or results from `runMSE` are sufficient

**Comment by quang-huynh** [comment]
`SSMOM2OM` converts an MOM generated by `SS2MOM` into an OM
https://github.com/Blue-Matter/MSEtool/commit/12e5e97b1308914e8667f3f3971579af019701bc
