### ISSUE TITLE
Add density-dependent M to OM and SCA (and RCM)

### ISSUE THREAD

**Issue by robynforrest** [Blue-Matter/MSEtool#27]
Following conversation with Tom (Dec 10 2020), I am adding this issue to add density dependent M option to OM and SCA MP. 

Natural mortality can be modeled as a function of total biomass, i.e., density-dependent M, using the following equation (Forrest et al. 2018; Eq 1): 

Mt = M0 + (M1 - M0)(1 – (Bt/B0))  [for Bt <= B0];  and
Mt = M0 [for Bt > B0]

Where Bt and B0 are total biomass; and M0 and M1 are constants. 
As Bt approaches B0, Mt approaches M0. 
As Bt approaches zero, Mt approaches M1. Therefore, as long as 0 < Bt <= B0, Mt is constrained between M1 and M0. An additional constraint is provided for Bt>B0 to stop negative or unconstrained increase in M. 
Also, if M0=M1, Mt is density-independent and Mt=M0.

A key property of this function is that when M1 < M0, mortality is compensatory (Mt decreases as Bt decreases). 
Conversely, when M1 > M0, mortality is depensatory (Mt increases as Bt decreases) (see Forrest et al. 2018).

Reference points can also be calculated that account for density-dependent M. However, there is a circularity problem, as M_eq relies on an estimate of equilibrium depletion (D_eq), which itself relies on M_eq. Forrest et al (2018) present a simple numerical algorithm (Appendix B), which iteratively solves for M_eq  and D_eq, conditioned on F_eq and the population parameters.

I can dig up the code if required.

Reference:
Forrest, R., Holt, K., and Kronlund, A. 2018. Performance of alternative harvest control rules for two Pacific groundfish stocks with uncertain natural mortality: Bias, robustness and trade-offs. Fisheries Research 206: 259–286. https://doi.org/10.1016/j.fishres.2018.04.007

**Comment by quang-huynh** [comment]
I think this is something we can already implement as a MICE interaction `M_1 = f(B_1)` (M of stock #1 is a function of stock #1 biomass) in `multiMSE`. We just have to create an object `x` that takes biomass as input and returns M (eq. 1) when we called by the generic `predict(x)`. Then, the reference points are calculated outside of openMSE. 

I'll give this a shot soon.
