### ISSUE TITLE
Allow for variable width length bins

### ISSUE THREAD

**Issue by quang-huynh** [Blue-Matter/MSEtool#31]
Variable width length bins are needed for several SS models (long-term priority)

**Comment by quang-huynh** [comment]
This feature was easy to implement: https://github.com/Blue-Matter/MSEtool/commit/4b67cd20c41c0a07e24276aad0afccefb0bef7cc

In this commit, only CAL_bins should be passed in as a cpars vector, because nCALbins, binWidth, CAL_binsmid can all be calculated afterwards from CAL_bins.

**Comment by AdrianHordyk** [comment]
Great. Have you checked if the simulated length comps work correctly - ie CAL_bins, binsmid, CAL, in the Data object are generated correctly in the OM, or does it need work on the OM side?

**Comment by quang-huynh** [comment]
Everything should be working with this commit to master: https://github.com/Blue-Matter/MSEtool/commit/f72f721b95ddf1237acab83ec29c60591b231b24 (previous one has been lost in all the merges!) with updates to SampleStockPars, simCAL, genSizeCompWrap, and associated Rcpp functions

By default, new simCAL generates the same length comps as previously:
```
Hist <- runMSE(Hist = TRUE)
identical(Hist@Data@CAL, SimulatedData@CAL) # returns TRUE
```

An example with unequal length bins:

```
testOM@cpars$CAL_bins <- c(0, 20, 40, 100, 200)
res <- runMSE(testOM, Hist = TRUE)
SAMtool::plot_composition(res@Data@Year, res@Data@CAL[1,,], CAL_bins = res@Data@CAL_mids)
```
