### ISSUE TITLE
Alternative CAA/CAL distributions

### ISSUE THREAD

**Issue by quang-huynh** [Blue-Matter/MSEtool#32]
Something I played around with to use the logistic-normal sampling distribution as an alternative to the multinomial: https://github.com/Blue-Matter/MSEtool/commit/232ae7590165217fb0fa43c3b45c9661fca6c1c2 Here, logistic-normal is used when CAA_ESS < 1. Logistic-normal is useful to avoid zeros. Primarily useful for a VPA that becomes more unstable when there are zeros in the CAA.

**Comment by AdrianHordyk** [comment]
Seems reasonable. Merge with master?

**Comment by quang-huynh** [comment]
I've updated the branch with the documentation to `simCAA`: https://github.com/Blue-Matter/MSEtool/commit/1eb9202851e29cd7a508db8d4d023d7368bc0239

It can now be merged into master, although it'd be nice to also update `ObsTemplate` (I couldn't find it in the repo).

Adding this feature to `simCAL` requires an extensive re-write although it's not a priority at this time.
