### ISSUE TITLE
SS2OM - Add Linf, K, and t0 to OM@cpars

### ISSUE THREAD

**Issue by AdrianHordyk** [Blue-Matter/MSEtool#35]
Fit vB model to the length-at-age for the last historical year and add to `cpars`, e.g., `OM@cpars$Linf = rep(100, OM@nsim)`

Otherwise this is done every time the OM is run in `runMSE`

**Comment by quang-huynh** [comment]
Currently I'm doing this, see CA Halibut. It would only fail if SS2OM can't find the parameters from r4ss. Is there an OM that is missing growth pars in cpars?

**Comment by AdrianHordyk** [comment]
This was an issue with the swordfish OMs, but they were created with an older version of SS2OM. Sounds like it's not an issue any more.
