### ISSUE TITLE
Export functions for AddIbeta and AddIerr calculations

### ISSUE THREAD

**Issue by quang-huynh** [Blue-Matter/MSEtool#42]
Currently these calculations are in a black box in `AddRealData()` and it will be helpful to see if estimates of beta, AC, etc are suitable (e.g. beta can difficult to obtain when there are few survey values or lack of contrast in the index) or whether they need to overridden in cpars.

**Comment by AdrianHordyk** [comment]
Currently the estimates for beta, AC, etc are returned in `ObsPars$AddInd_Stat`  for additional indices, and `ObsPars$Ierr_y` and `ObsPars$I_beta` for `Data@Ind`. 

Agree that it would be useful to export the functions and make this an explicit part of the workflow. Something like:
```
OM@cpars$Data <- Data
Hist <- runMSE(OM)
Report(OM)
# examine observation parameters
MSE <- Simulate(Hist,...)
```

**Comment by quang-huynh** [comment]
Good to know. This should work for me for now, but agree that it'll be nice to have a comprehensive OM/Hist report.
