### ISSUE TITLE
Skipjack_IO_IOTC OM from MSEtool Extra not compatible

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/MSEtool#44]
Returns error: 

Set OM@nsim = 24 

Loading operating model 

Invalid names found in custom parameters: 

  not_used_cpars
1      plusgroup
Valid custom parameters found: Len_age Wt_age Mat_age M_ageArray Perr_y V Find 

Warning: Error in SampleStockPars: 'Len_age' must be array with dimensions: nsim, maxage+1, nyears + proyears. 
Should be: 24,9,117; Currently is: 24,8,117

**Comment by AdrianHordyk** [comment]
Fixed
