### ISSUE TITLE
get an acf() error when submitting data with an index with only one observation

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/MSEtool#47]
[data.zip](https://github.com/Blue-Matter/MSEtool/files/6367720/data.zip)

with this data and OM run:

Fit<-RCM(OM, data, condition="catch2", selectivity="dome", s_selectivity="logistic", 
         mean_fit=T, cores=4, drop_nonconv=T, drop_highF=T,  LWT = list(CAL = 0.1, s_CAL = 10))

plot(Fit)

to see the issue

**Comment by AdrianHordyk** [comment]
Seems to be fixed now.
