### ISSUE TITLE
Strange LinInterp behavior

### ISSUE THREAD

**Issue by quang-huynh** [Blue-Matter/MSEtool#52]
The current LinInterp function returns Inf in the simple case of knife-edge maturity/selectivity:

```
x <- c(rep(0, 2), rep(1, 8))
y <- 1:10
MSEtool:::LinInterp(x, y, 0.5)
```

Thus, SampleStockPars returns ageM of maxage - 1.

I've added an alternative interpolation using the approx function https://github.com/Blue-Matter/MSEtool/commit/56f7a30835a79ce68e2b082c75e94671487975f5 which appears to be more robust:

```
MSEtool:::LinInterp(x, y, 0.5, method = "approx") # calls: approx(x, y, 0.5)
```

Should we switch over to approx? I haven't been able to speed compare approx with LinInterp_cpp due to https://github.com/Blue-Matter/MSEtool/issues/51

**Comment by AdrianHordyk** [comment]
Yea, makes sense to switch to `approx` instead and remove the cpp version. We need to add checks for attempting to interpolate beyond range of `x` & `y` as well.

**Comment by quang-huynh** [comment]
From the microbenchmark test, the cpp version is still an order of magnitude faster than approx so the former is still worth keeping for `per_recruit_calc_F`. The cpp code is fine for monotically decreasing functions like SPR
