### ISSUE TITLE
plot(OM) and plot(RCMfit) plots would be greatly improved by simple addition of grid() or equivalent

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/MSEtool#72]
Self explanatory, without reference lines the plots are much harder to read

**Comment by quang-huynh** [comment]
Base R graphics by default don't have grid lines so we'd have them
manually. ggplot does have grid lines but I think they'd really slow down
the markdown rendering?

**Comment by quang-huynh** [comment]
Best solution is to add this function internally:

```
plot.default <- function(...) graphics::plot.default(..., panel.first = graphics::grid())
```

See https://github.com/Blue-Matter/SAMtool/commit/46dc4cec20440dd80bb539f6f8728f767e8468e5
