### ISSUE TITLE
Deprecating/archiving CRAN version of {r4ss} package

### ISSUE THREAD

**Issue by iantaylor-NOAA** [Blue-Matter/MSEtool#76]
The {r4ss} package is a suggested dependency by {MSEtool}: https://github.com/Blue-Matter/MSEtool/blob/b23856cdd9aedfbd0ef54d7c2b2dc32be4117a9d/DESCRIPTION#L45

The CRAN version of {r4ss} (along with {ss3sim} maintained by @kellijohnson-NOAA) is out of date and making time to submit updates to CRAN has been a struggle. Therefore we are thinking of [requesting that these packages be archived](https://cran.r-project.org/web/packages/policies.html#:~:text=Packages%20will%20not%20normally%20be%20removed%20from%20CRAN). 

I see that MSEtool already suggests installing {r4ss} from github at 
https://github.com/Blue-Matter/MSEtool/blob/b23856cdd9aedfbd0ef54d7c2b2dc32be4117a9d/R/SSinternal.R#L4 
but I wanted to let you know of this plan in case it has any impact on your package.

Let me know if you have any questions, comments, or concerns.

**Comment by AdrianHordyk** [comment]
Thanks for the heads-up @iantaylor-NOAA 
It should be ok because `r4ss` is listed under `Suggests` but will look out for issues if/when `r4ss` is archived on CRAN

**Comment by iantaylor-NOAA** [comment]
Got it. Thank you.
