### ISSUE TITLE
OM@L50 and OM@L50_95 not worked as expected  for some OMs when using plot(OM) at least

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/MSEtool#85]
[Blood Snapper FMA 718.zip](https://github.com/Blue-Matter/MSEtool/files/13291055/Blood.Snapper.FMA.718.zip)

OM@L50
OM@L50_95
plot(OM)

**Comment by tcarruth** [comment]
This might actually be an issue with RCM - there is a cpars$mat_age array that comes from RCM in this example

**Comment by quang-huynh** [comment]
Fixed here - https://github.com/Blue-Matter/SAMtool/issues/50
