### ISSUE TITLE
Format of PPD in MMSE object

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/MSEtool#88]
One of the useful things about the posterior predicted data is to be able to generate this for MP development and testing.

However the format of this differs between MMP and MMSE. 

MMP accepts a DataList object DataList[[stock]][[fleet]]

Whereas the posterior predicted data are stored as MMSE@PPD[[stock]][[fleet]][[1]] which means it is not quite as easy to use the PPD for MP development.

**Comment by AdrianHordyk** [comment]
```
select_MP <- function(PPD, MP=1) {
  DataList <- vector('list', length(PPD))
  for (s in 1:length(DataList)) {
    DataList[[s]] <- vector('list', length(PPD[[s]]))
    for (f in 1:length(DataList[[s]])) {
      DataList[[s]][[f]] <- PPD[[s]][[f]][[MP]]
    }
  }
  DataList
}
```

Added to `MSEtool`
