### ISSUE TITLE
predictMK returns error with inpars argument

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/MSEtool#90]
library(MSEtool)
predictLH(Genus ="Strongylocentrotus", Species = "droebachiensis",nsamp=1000,inpars = list("L50"))

"Error in 0.95 * Out$Linf : non-numeric argument to binary operator"

**Comment by AdrianHordyk** [comment]
need to add lower and upper bounds to `inpars`

eg 
`predictLH(Genus ="Strongylocentrotus", Species = "droebachiensis",nsamp=1000,inpars = list("L50"=c(100,200)))`
